# Generated by Django 3.2.4 on 2021-06-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('avatar', models.ImageField(default='default_avatar.jpg', upload_to='', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Short biography')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('join_date', models.DateTimeField(blank=True, null=True, verbose_name='Join date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Admin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
