# Generated by Django 3.2.4 on 2021-06-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_article_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='can_comment',
            field=models.BooleanField(default=True),
        ),
    ]
