# Generated by Django 3.2.4 on 2021-06-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_article_can_comment'),
        ('app_comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(limit_choices_to={'can_comment': True, 'status': 'P'}, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_blog.article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sub_comment',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_sub': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='app_comment.comment'),
        ),
    ]
